In [ ]:
import numpy as np
import random

a,b,c,d=random.randint(-100,100),random.randint(-100,100),random.randint(-100,100),random.randint(-100,100)
s1=str(a)+' '+str(b)+';'+str(c)+' '+str(d)
A=np.mat(s1)
x,y=random.randint(-100,100),random.randint(-100,100)
s2=str(x)+';'+str(y)
v=np.mat(s2)
for i in range(2000):
    z=A*v
    z=z/np.linalg.norm(z)
    v=z
    print(v)

[[-0.73537045]
 [-0.67766533]]
[[-0.86320464]
 [ 0.50485419]]
[[-0.36586204]
 [ 0.9306691 ]]
[[0.46088532]
 [0.8874597 ]]
[[ 0.9578506 ]
 [-0.28726681]]
[[ 0.50391291]
 [-0.86375447]]
[[-0.19527111]
 [-0.9807493 ]]
[[-0.99997085]
 [-0.00763483]]
[[-0.6311826 ]
 [ 0.77563427]]
[[-0.02851463]
 [ 0.99959338]]
[[0.93288062]
 [0.36018572]]
[[ 0.75192434]
 [-0.65924941]]
[[ 0.21276603]
 [-0.97710318]]
[[-0.73048574]
 [-0.68292794]]
[[-0.865266  ]
 [ 0.50131302]]
[[-0.36865872]
 [ 0.92956481]]
[[0.45550265]
 [0.89023443]]
[[ 0.95931014]
 [-0.28235447]]
[[ 0.50644119]
 [-0.8622745 ]]
[[-0.19055017]
 [-0.98167746]]
[[-0.99990145]
 [-0.01403904]]
[[-0.63355714]
 [ 0.77369591]]
[[-0.03239578]
 [ 0.99947512]]
[[0.93020834]
 [0.36703195]]
[[ 0.75418727]
 [-0.6566594 ]]
[[ 0.21599256]
 [-0.97639501]]
[[-0.72557375]
 [-0.68814441]]
[[-0.86732093]
 [ 0.49774934]]
[[-0.37144881]
 [ 0.92845344]]
[[0.45012574]
 [0.89296518]]
[[ 0.96075091]
 [-0.27741248]]
[[ 0.50896563]
 [-0.86078684]]
[[-0.18584578]
 [-

**Conclusion** : "applying the matrix, normalize and repeat" makes any random vector converge to normalized eigenvector of the matrix.

In [ ]:
'''exceptions'''

#s1 : 43 -25;23 -92
#s2 : 74;24
#alternates between [[-0.18801449],[-0.98216625]] and [[0.18801449],[0.98216625]]
#negative eigenvalue
print()
#s1 : -26 -63;-75 -19
#s2 : -1;75
#alternates between [[-0.69416668],[-0.7198143 ]] and [[0.69416668],[0.7198143]]
#negative eigenvalue

#s1 : 10 71;-70 -28
#s2 : 31;67
#does not converge even after 2000 iterations

#s1 : 63 49;-78 16
#s2 : 18;-84
#does not converge even after 2000 iterations

print(s1,s2,sep='\n') 

63 49;-78 16
18;-84
